version: '3'

services: 
  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - "80:8080"
  #     - "5432"
  #   volumes:
  #     - ../:/code
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./frontend:/var/www/frontend
  #   # depends_on:
  #   #   - backend

  db:
    restart: unless-stopped
    image: postgres:10.1-alpine
    ports: 
      # - "127.0.0.1:5432:5432"
      - "5432"

  backend:
    build: ../shops_app/docker/
    depends_on:
      - db
      # - nginx

    # restart: unless-stopped

    # command: bash -c "
    #                   python manage.py migrate &&
    #                   python manage.py makemigrations --no-input &&
    #                   python manage.py test"

    command: bash -c "
                      python manage.py makemigrations --no-input &&
                      python manage.py migrate &&
                      python manage.py collectstatic --no-input &&
                      gunicorn shops_app.wsgi -b 0.0.0.0:8000"

    # command: bash -c "cd shop_app_backend && 
    #                   gunicorn shop_app_backend.wsgi -b 0.0.0.0:8000"
   
    volumes:
      - ../shops_app:/code
    ports:
      - "8000:8000"